CREATE DATABASE IF NOT EXISTS spacetech;

USE spacetech;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    USUARIO VARCHAR(40) UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    TELEFONE VARCHAR(15) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    NOME_CARGO VARCHAR(100) NOT NULL,
    NIVEL_PERMISSAO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDO (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(400) NOT NULL,
    STATUS_PEDIDO VARCHAR(20) NOT NULL,
    NOME_CLIENTE VARCHAR(40) NOT NULL,
    EMAIL_CLIENTE VARCHAR(40) NOT NULL,
    CPF_CLIENTE CHAR(14) NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    NOME_VENDEDOR VARCHAR(40) NOT NULL,
    CPF_VENDEDOR VARCHAR(14) NOT NULL,
    ID_GERENTE INT,
    NOME_GERENTE VARCHAR(40),
    CPF_GERENTE VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS ATENDIMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_CLIENTE INT NOT NULL,
    SERVICO VARCHAR(100) NOT NULL,
    NOME_CLIENTE VARCHAR(400) NOT NULL,
    CPF_CLIENTE CHAR(14) NOT NULL,
    EMAIL_CLIENTE VARCHAR(40) NOT NULL,
    TELEFONE_CLIENTE CHAR(15) NOT NULL,
    STATUS_ATENDIMENTO VARCHAR(14) NOT NULL,
    ID_VENDEDOR INT,
    NOME_VENDEDOR VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS CARGO (
    ID INT PRIMARY KEY NOT NULL,
    TITULO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAMADO (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    NIVEL VARCHAR(20) NOT NULL,
    STATUS_CHAMADO VARCHAR(20) NOT NULL,
    ID_USUARIO INT NOT NULL,
    NOME_USUARIO VARCHAR(80) NOT NULL,
    ID_ANALISTA INT,
    NOME_ANALISTA VARCHAR(40)
);

INSERT INTO CARGO VALUES (1, "Cliente"), (2, "Vendedor"), (3, "Gerente"), (4, "ADMINISTRADOR");

INSERT INTO `usuario` (`ID`, `USUARIO`, `NOME`, `SOBRENOME`, `EMAIL`, `CPF`, `TELEFONE`, `SENHA`, `NOME_CARGO`, `NIVEL_PERMISSAO`) VALUES
(1, 'admin', 'admin', 'permission', 'admin@space.com', '000.000.000-00', '(14) 0000-0000', 'c3284d0f94606de1fd2af172aba15bf3', 'administrador', 4)

